---
title: "MOSAIC R packages"
description: |
  The various R packages produced by the MOSAIC team.
---

The following packages are part of the "mosaic suite". All are available
on CRAN and maintained on GitHub.

* [`{mosaic}`](https://www.mosaic-web.org/mosaic/)
    - `{mosaicCore}` Contains helper functions. Automatically installed when `{mosaic}` is installed from CRAN.
* [`{mosaicData}`](http://www.mosaic-web.org/mosaicData/)
* [`{mosaicCalc}`](https://github.com/ProjectMOSAIC/mosaicCalc) -- Completely updated in 2022 to provide better symbolic capabilities while retaining the ease of use of the formula interface. The vignettes give a good introduction to the package. See the [**Mosaic Calculus**](https://www.mosaic-web.org/MOSAIC-Calculus/) textbook for many more examples.

* [`{ggformula}`](https://www.mosaic-web.org/ggformula/) provides a formula-based interface
to the popular `ggplot2` graphics system. Some advantages:
    - uses the standard pipe operator (either `%>%` or the newer `|>`) instead of the ideosyncratic `+` of `ggplot2`.
    - one-liner commands with fewer parentheses: `Galton |> gf_point(height ~ mother)` compared to `Galton |> ggplot2(aes(x=mother, y=height)) + geom_point()`
    - Inter-operates with `ggplot2()` and all related packages.
    - Provides an easy path to learning `lm()`
* [`{LST}`](https://github.com/dtkaplan/LST) provides support for the textbook  [*Lessons in Statistical Thinking*](https://dtkaplan.github.io/Lessons-in-statistical-thinking/). `{LST}` provides highly integrated, introductory-level graphics and modeling in the modern *Tidyverse* style. Install with `remotes::install_github("dtkaplan/LST")`. 

* Deprecated: [`{mosaicModel}`](https://www.mosaic-web.org/mosaicModel/) -- This package is retained for compatibility with the [DataCamp courses on statistical modeling](https://www.datacamp.com/courses/introduction-to-statistical-modeling-in-r). Many of the features have been transferred to the core mosaic packages listed above.
