---
title: "MOSAIC Datasets"
description: |
    Finding datasets from Project MOSAIC
---

The actively currated datasets are in the `{mosaicData}` R package.

## Supplemental data for *Lessons in Statistical Thinking*

These have documentation in the `{LSTbook}` package, but the data themselves need to be `load()`ed as a URL. This is to keep the `{LSTbook}` package small by not including large datasets that are rarely used.

- [Natality_2014](datasets/Natality_2014.rda)  

`load("https://www.mosaic-web.org/go/datasets/Natality_2014.rda")`

- [Weights and lengths of trout](datasets/trout-perch.csv) This is from Douglas Whitaker's 2021 activity on [Stew](https://www.amstat.org/education/stew/statistics-education-web-(stew)): "Nonlinear Modeling: Something Fishy"

`Trout <- read.csv("https://www.mosaic-web.org/go/datasets/trout-perch.csv")


## Legacy links

There are some legacy datasets (from before the R-package era), many but not all of which were incorporated in `{mosaicData}` 

<ul>
<li><a href="datasets/alder.csv" class="uri">alder.csv</a></li>
<li><a href="datasets/cardata.csv" class="uri">cardata.csv</a></li>
<li><a href="datasets/Cherry-Blossom-2008.csv" class="uri">Cherry-Blossom-2008.csv</a></li>
<li><a href="datasets/congress.csv" class="uri">congress.csv</a></li>
<li><a href="datasets/Dome.csv" class="uri">Dome.csv</a></li>
<li><a href="datasets/engines.csv" class="uri">engines.csv</a></li>
<li><a href="datasets/gestation.csv" class="uri">gestation.csv</a></li>
<li><a href="datasets/hawaii.csv" class="uri">hawaii.csv</a></li>
<li><a href="datasets/kepler-mars.csv" class="uri">kepler-mars.csv</a></li>
<li><a href="datasets/Income-Housing.csv" class="uri">Income-Housing.csv</a></li>
<li><a href="datasets/Inflation.csv" class="uri">Inflation.csv</a></li>
<li><a href="datasets/kidsfeet.csv" class="uri">kidsfeet.csv</a></li>
<li><a href="datasets/myopia.csv" class="uri">myopia.csv</a></li>
<li><a href="datasets/oring-damage.csv" class="uri">oring-damage.csv</a></li>
<li><a href="datasets/repeat-runners.csv" class="uri">repeat-runners.csv</a></li>
<li><a href="datasets/running-longitudinal.csv" class="uri">running-longitudinal.csv</a></li>
<li><a href="datasets/SaratogaHouses.csv" class="uri">SaratogaHouses.csv</a></li>
<li><a href="datasets/tadpole.csv" class="uri">tadpole.csv</a></li>
<li><a href="datasets/ten-mile-race.csv" class="uri">ten-mile-race.csv</a></li>
<li><a href="datasets/truckingjobs.csv" class="uri">truckingjobs.csv</a></li>
<li><a href="datasets/used-fords.csv" class="uri">used-fords.csv</a></li>
<li><a href="datasets/used-hondas.csv" class="uri">used-hondas.csv</a></li>
<li><a href="datasets/whickham.csv" class="uri">whickham.csv</a></li>
<li><a href="datasets/zebra-mussels.csv" class="uri">zebra-mussels.csv</a></li>
</ul>
